
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author win10
 */
public class admin extends javax.swing.JFrame {

    public String email;

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
    }

    admin(String userEmail) {
        initComponents();
        email = userEmail;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnAddStaff = new javax.swing.JButton();
        BtnManageStaff = new javax.swing.JButton();
        txtProfile = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnAddMedicine = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        btnDeleteMedicine = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        btnUpdateStaff = new javax.swing.JToggleButton();
        btnUpdateMedicine = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 613));
        setMinimumSize(new java.awt.Dimension(900, 613));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 613));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/icons8-multiply-50.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 30, 30));

        btnAddStaff.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAddStaff.setText("Add Staff");
        btnAddStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStaffActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 197, -1));

        BtnManageStaff.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BtnManageStaff.setText("View Staff");
        BtnManageStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManageStaffActionPerformed(evt);
            }
        });
        getContentPane().add(BtnManageStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 197, -1));

        txtProfile.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtProfile.setText("Profile");
        txtProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfileActionPerformed(evt);
            }
        });
        getContentPane().add(txtProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 224, -1));

        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLogOut.setText("Logout");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 224, -1));

        btnAddMedicine.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAddMedicine.setText("Add Medicine");
        btnAddMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMedicineActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 197, -1));

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton7.setText("View Medicine");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        btnDeleteMedicine.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDeleteMedicine.setText("Delete Medicine");
        btnDeleteMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMedicineActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 224, -1));

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton9.setText("Total Sales");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 224, -1));

        btnUpdateStaff.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUpdateStaff.setText("Update Staff");
        btnUpdateStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStaffActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 197, -1));

        btnUpdateMedicine.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnUpdateMedicine.setText("Update Medicine");
        btnUpdateMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMedicineActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/Interface one.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to close the Application", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Logout", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new login().setVisible(true);
        }

    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnAddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStaffActionPerformed
        // TODO add your handling code here:
        
        new addStaff().setVisible(true);
    }//GEN-LAST:event_btnAddStaffActionPerformed

    private void BtnManageStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManageStaffActionPerformed
        // TODO add your handling code here:
        
        new ViewUser().setVisible(true);
    }//GEN-LAST:event_BtnManageStaffActionPerformed

    private void btnUpdateStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStaffActionPerformed
        // TODO add your handling code here:
         
        new UpdateStaff().setVisible(true);
    }//GEN-LAST:event_btnUpdateStaffActionPerformed

    private void txtProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfileActionPerformed
        // TODO add your handling code here:
        
        new profile(email).setVisible(true);
    }//GEN-LAST:event_txtProfileActionPerformed

    private void btnAddMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMedicineActionPerformed
        // TODO add your handling code here:
        ;
        new AddMedicine().setVisible(true);
    }//GEN-LAST:event_btnAddMedicineActionPerformed

    private void btnUpdateMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMedicineActionPerformed
        // TODO add your handling code here:
        
        new updateMedicine().setVisible(true);
    }//GEN-LAST:event_btnUpdateMedicineActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new viewMedicine().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnDeleteMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMedicineActionPerformed
        // TODO add your handling code here:
        new deleteMedicine().setVisible(false);
    }//GEN-LAST:event_btnDeleteMedicineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnManageStaff;
    private javax.swing.JButton btnAddMedicine;
    private javax.swing.JButton btnAddStaff;
    private javax.swing.JButton btnDeleteMedicine;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnUpdateMedicine;
    private javax.swing.JToggleButton btnUpdateStaff;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton txtProfile;
    // End of variables declaration//GEN-END:variables
}
